### PR TITLE
Custom richtext spans

### PR DESCRIPTION
**Pull request by Wavesonics**
This might be obviated by the changes you just pushed? But if not, does this look like the right direction for users to be able to provide their own RichSpans?

### CODE REVIEW

**Comment by MohamedRejeb** [comment]
LGTM, it's going in the right direction. The `drawCustomStyle` method is made specifically for the code span, so feel free to change its parameters if you have a better idea.

**Comment by Wavesonics** [comment]
Okay, I think it's good to go

**Review by MohamedRejeb — APPROVED** [review]
Thanks you!

**Comment by MohamedRejeb** [comment]
Closes: #135

**Pull request merged**
