### PR TITLE
Add Link Handling For the Hyperlink RichText

### PR DESCRIPTION
**Pull request by DAKSHSEMWAL**
Handles HyperLink for RichText but needs some fixes for the Editor

### CODE REVIEW

**Comment by MohamedRejeb** [comment]
Thanks for contributing, I will take a look at this

**Comment by DAKSHSEMWAL** [comment]
Added the fix for crash on the RichTextEditor

**Comment by MohamedRejeb** [comment]
Good, I'm working on a new foundation for the library that's why I didn't check this PR yet, I need to check after completing the new foundation.

**Comment by DAKSHSEMWAL** [comment]
@AzimMuradov this one just deals with Hyperlinks so ,We can merge this one first

**Pull request merged**
